CART_HOST: cart.backend-{{ env }}.akinfotech.site
USER_HOST: user.backend-{{ env }}.akinfotech.site
RABBITMQ_HOST: rqbbitmq-{{ env}}.akinfotech.site
RABBITMQ_USER: roboshop
RABBITMQ_PASSWORD: roboshop123